//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttributeGroup
    {
        public AttributeGroup()
        {
            this.AttributeGroupItems = new HashSet<AttributeGroupItem>();
            this.Products = new HashSet<Product>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int OutletId { get; set; }
    
        public virtual Outlet Outlet { get; set; }
        public virtual ICollection<AttributeGroupItem> AttributeGroupItems { get; set; }
        public virtual ICollection<Product> Products { get; set; }
    }
}
