//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttributeItem
    {
        public AttributeItem()
        {
            this.OrderItemAttributeItems = new HashSet<OrderItemAttributeItem>();
        }
    
        public int Id { get; set; }
        public int AttributeId { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public string Description { get; set; }
        public int DisplayOrder { get; set; }
        public bool DefaultSelected { get; set; }
        public Nullable<int> SelectionTypeId { get; set; }
        public string DefaultSelectionTypeValue { get; set; }
        public bool Published { get; set; }
        public bool Deleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    
        public virtual Attribute Attribute { get; set; }
        public virtual SelectionType SelectionType { get; set; }
        public virtual ICollection<OrderItemAttributeItem> OrderItemAttributeItems { get; set; }
    }
}
