//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuisine
    {
        public Cuisine()
        {
            this.OutletCuisineMappings = new HashSet<OutletCuisineMapping>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int DisplayOrder { get; set; }
    
        public virtual ICollection<OutletCuisineMapping> OutletCuisineMappings { get; set; }
    }
}
