//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.CouponOrderMappings = new HashSet<CouponOrderMapping>();
            this.CustomerAddresses = new HashSet<CustomerAddress>();
            this.CustomerHistories = new HashSet<CustomerHistory>();
            this.CustomerTokens = new HashSet<CustomerToken>();
            this.CustomerVerifications = new HashSet<CustomerVerification>();
            this.Orders = new HashSet<Order>();
            this.SearchLogs = new HashSet<SearchLog>();
            this.Logs = new HashSet<Log>();
            this.Outlets = new HashSet<Outlet>();
            this.Outlets1 = new HashSet<Outlet>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string MobileNumber { get; set; }
        public bool EmailVerified { get; set; }
        public bool MobileVerified { get; set; }
        public string FacebookId { get; set; }
        public string GoogleId { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public Nullable<int> BillingAddressId { get; set; }
        public Nullable<int> ShippingAddressId { get; set; }
        public string PasswordSalt { get; set; }
        public Nullable<int> CustomerRoleId { get; set; }
        public bool Deleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    
        public virtual ICollection<CouponOrderMapping> CouponOrderMappings { get; set; }
        public virtual CustomerRole CustomerRole { get; set; }
        public virtual ICollection<CustomerAddress> CustomerAddresses { get; set; }
        public virtual ICollection<CustomerHistory> CustomerHistories { get; set; }
        public virtual ICollection<CustomerToken> CustomerTokens { get; set; }
        public virtual ICollection<CustomerVerification> CustomerVerifications { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<SearchLog> SearchLogs { get; set; }
        public virtual ICollection<Log> Logs { get; set; }
        public virtual ICollection<Outlet> Outlets { get; set; }
        public virtual ICollection<Outlet> Outlets1 { get; set; }
    }
}
