//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportMenuTemp
    {
        public int Id { get; set; }
        public string Category1 { get; set; }
        public string Category2 { get; set; }
        public string Item { get; set; }
        public string DisplayName { get; set; }
        public string Price { get; set; }
        public string Variety1 { get; set; }
        public string Variety1Price { get; set; }
        public string Variety2 { get; set; }
        public string Variety2Price { get; set; }
        public string Variety3 { get; set; }
        public string Variety3Price { get; set; }
        public string Variety4 { get; set; }
        public string Variety4Price { get; set; }
        public string Lunch { get; set; }
        public string Dinner { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<int> VarietyID1 { get; set; }
        public Nullable<int> VarietyID2 { get; set; }
        public Nullable<int> VarietyID3 { get; set; }
        public Nullable<int> VarietyID4 { get; set; }
        public string IsNonVeg { get; set; }
        public string Description { get; set; }
    }
}
