//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTax
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public int TaxGroupItemId { get; set; }
        public string TaxName { get; set; }
        public int CalculateOrder { get; set; }
        public int TaxType { get; set; }
        public decimal Rate { get; set; }
        public Nullable<int> CalculateOn { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public int DisplayOrder { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual TaxGroupItem TaxGroupItem { get; set; }
    }
}
