//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public OrderItem()
        {
            this.OrderItemAttributeItems = new HashSet<OrderItemAttributeItem>();
        }
    
        public int Id { get; set; }
        public int OrderId { get; set; }
        public int ProductId { get; set; }
        public decimal ItemPrice { get; set; }
        public int Quantity { get; set; }
        public Nullable<int> ItemDeliveryTypeId { get; set; }
        public decimal Amount { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual ICollection<OrderItemAttributeItem> OrderItemAttributeItems { get; set; }
    }
}
