//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.CouponOrderMappings = new HashSet<CouponOrderMapping>();
            this.OrderHistories = new HashSet<OrderHistory>();
            this.OrderItems = new HashSet<OrderItem>();
            this.OrderTaxes = new HashSet<OrderTax>();
            this.OrderNotes = new HashSet<OrderNote>();
        }
    
        public int Id { get; set; }
        public string OrderNo { get; set; }
        public int CustomerId { get; set; }
        public int OutletId { get; set; }
        public int OrderStatusId { get; set; }
        public Nullable<int> ShippingAddressId { get; set; }
        public Nullable<int> BillingAddressId { get; set; }
        public int OrderDeliveryTypeId { get; set; }
        public decimal SubTotal { get; set; }
        public decimal ShippingTotal { get; set; }
        public decimal DiscountTotal { get; set; }
        public decimal OrderTotal { get; set; }
        public string CouponCode { get; set; }
        public string Comment { get; set; }
        public Nullable<int> OrderSourceId { get; set; }
        public Nullable<System.DateTime> DeliveryDateTime { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual ICollection<CouponOrderMapping> CouponOrderMappings { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual CustomerAddress CustomerAddress { get; set; }
        public virtual CustomerAddress CustomerAddress1 { get; set; }
        public virtual OrderDeliveryType OrderDeliveryType { get; set; }
        public virtual OrderSource OrderSource { get; set; }
        public virtual Outlet Outlet { get; set; }
        public virtual ICollection<OrderHistory> OrderHistories { get; set; }
        public virtual ICollection<OrderItem> OrderItems { get; set; }
        public virtual ICollection<OrderTax> OrderTaxes { get; set; }
        public virtual ICollection<OrderNote> OrderNotes { get; set; }
    }
}
