//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutletBanquet
    {
        public OutletBanquet()
        {
            this.BanquetEnquiries = new HashSet<BanquetEnquiry>();
            this.BanquetImageGallaries = new HashSet<BanquetImageGallary>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> MinimumCapacity { get; set; }
        public Nullable<int> MaximumCapacity { get; set; }
        public bool IsProjectorOrDisplayScreen { get; set; }
        public bool IsMusicSystem { get; set; }
        public bool IsAirConditioner { get; set; }
        public bool IsDecoration { get; set; }
        public bool IsMic { get; set; }
        public bool IsSpeechDesk { get; set; }
        public bool IsInternetOrWifi { get; set; }
        public bool IsStage { get; set; }
        public string Note { get; set; }
        public int OutletId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<BanquetEnquiry> BanquetEnquiries { get; set; }
        public virtual ICollection<BanquetImageGallary> BanquetImageGallaries { get; set; }
        public virtual Outlet Outlet { get; set; }
    }
}
