//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.OutletProductExcludes = new HashSet<OutletProductExclude>();
            this.ProductCategoryMappings = new HashSet<ProductCategoryMapping>();
        }
    
        public int Id { get; set; }
        public int OutletId { get; set; }
        public string Name { get; set; }
        public string DisplayName { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public bool IsVeg { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> AttributeGroupId { get; set; }
        public bool Published { get; set; }
        public bool Deleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public Nullable<int> OldId { get; set; }
        public Nullable<int> OldParentId { get; set; }
        public bool HasVariants { get; set; }
    
        public virtual AttributeGroup AttributeGroup { get; set; }
        public virtual Outlet Outlet { get; set; }
        public virtual ICollection<OutletProductExclude> OutletProductExcludes { get; set; }
        public virtual ICollection<ProductCategoryMapping> ProductCategoryMappings { get; set; }
    }
}
